### ISSUE TITLE
Latest PCB Design

### ISSUE THREAD

**Issue by zoon81** [M4GNV5/DocGreenESA5000-Dashboard#7]
Hi,

I just get this scooter and I love your dashboard project. Is the latest pcb design available?
Can you send a link to it?
Thank you and congrats!

**Comment by M4GNV5** [comment]
Hey,

i haven't ordered and tested the latest design yet, it includes some improvements to WiFi/BLE connectivity and has 10 WS2812 mini LEDs for displaying information during drive, as people had problems with OLED brightness:

![](https://i.m4gnus.de/1749b8.png)

I still have some of the previous version laying around (soldered and unsoldered) though if you want one? This one:
![](https://i.m4gnus.de/12d799.JPG)

Currently the PCB design isnt open source, people already started making money from the stuff in this repo by selling tuning chips on ebay, so im not sure if it ever will be open sourced :disappointed:

**Comment by zoon81** [comment]
Thank you, and I totally understood you opinion about making the design open source.
I think I need only one pcb so I will put it on protoboard. Do you think that the display is not made for something like this?
I thought that the OLED is fine outside, but actually I never tried it. Maybe the cover just shade it too much.

**Comment by M4GNV5** [comment]
OLEDs are fine outside. Its still readable, but it feels more like reading the station name on the radio in a car (i.e. 2-3 seconds distraction) rather than briefly looking at the displayed speed (i.e. 1-2 seconds distraction) if you know what i mean.

As github doesnt have direct messages feel free to send me a mail if you are interested in one of the PCBs.
